### ISSUE TITLE
Fix OSRMTextInstructionsFixturesTest failing from too many open files

### ISSUE THREAD

**Issue by bitsondatadev** [brianolsen87/text-instructions#1]
OSRMTextInstructionsFixturesTest seems to run all the fixture tests if they are ran individually but running all the tests consecutively results in a mac error that seems to be common to nodejs due to opening too many files.

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EMFILE: too many open files, open '/private/var/folders/pm/pcgz4z9x30512cv0ldhkb69wtksjzw/T/startup4345070119053964816.js.tmp'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.Module._extensions..js (module.js:421:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

Tried increasing maxfiles limit as suggested by SO but it didn't solve my issue yet. Will come back to this.

https://stackoverflow.com/questions/19981065/nodejs-error-emfile-too-many-open-files-on-mac-os

**Comment by bitsondatadev** [comment]
This was "fixed" in part by refactoring my tests in a way that didn't try opening too many J2V8 node instances at once. I was creating a new J2V8 instance for every fixture we had to test. This was not only time consuming but led to too many files being opened simultaneously and ultimately caused the error you see above. 

_Takeaway_: Whenever possible, try to register a singleton instance of the OSRMTextInstructions object to avoid this area. If one instance does not fit your use case then you must be careful not to make too many instances at once.
